package com.mcmoddev.ironagefurniture;

import net.minecraft.block.Block;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ObjectHolder;

@Mod.EventBusSubscriber(modid = Ironagefurniture.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
@ObjectHolder(Ironagefurniture.MODID)
public class BlockObjectHolder {
	public static final Block chair_wood_ironage_classic_oak = null;
	public static final Block chair_wood_ironage_classic_acacia = null;
	public static final Block chair_wood_ironage_classic_dark_oak = null;
	public static final Block chair_wood_ironage_classic_birch = null;
	public static final Block chair_wood_ironage_classic_jungle = null;
	public static final Block chair_wood_ironage_classic_spruce = null;
	
	public static final Block chair_wood_ironage_shield_oak = null;
	public static final Block chair_wood_ironage_shield_acacia = null;
	public static final Block chair_wood_ironage_shield_dark_oak = null;
	public static final Block chair_wood_ironage_shield_birch = null;
	public static final Block chair_wood_ironage_shield_jungle = null;
	public static final Block chair_wood_ironage_shield_spruce = null;		
	
	public static final Block chair_wood_ironage_stool_short_oak = null;
	public static final Block chair_wood_ironage_stool_short_acacia = null;
	public static final Block chair_wood_ironage_stool_short_dark_oak = null;
	public static final Block chair_wood_ironage_stool_short_birch = null;
	public static final Block chair_wood_ironage_stool_short_jungle = null;
	public static final Block chair_wood_ironage_stool_short_spruce = null;
	
	public static final Block chair_wood_ironage_stool_tall_acacia = null;
	public static final Block chair_wood_ironage_stool_tall_dark_oak = null;
	public static final Block chair_wood_ironage_stool_tall_birch = null;
	public static final Block chair_wood_ironage_stool_tall_jungle = null;	
	public static final Block chair_wood_ironage_stool_tall_oak = null;
	public static final Block chair_wood_ironage_stool_tall_spruce = null;
//	
//	public static final Block chair_wood_ironage_classic_biomesoplenty_cherry = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_ebony = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_ethereal = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_eucalyptus = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_fir = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_hellbark = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_jacaranda = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_magic = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_mahogany = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_mangrove = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_palm = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_pine = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_redwood = null; 
//	public static final Block chair_wood_ironage_classic_biomesoplenty_sacred_oak = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_umbran = null;
//	public static final Block chair_wood_ironage_classic_biomesoplenty_willow = null;
//	
//	public static final Block chair_wood_ironage_shield_biomesoplenty_cherry = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_ebony = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_ethereal = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_eucalyptus = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_fir = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_hellbark = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_jacaranda = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_magic = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_mahogany = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_mangrove = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_palm = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_pine = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_redwood = null; 
//	public static final Block chair_wood_ironage_shield_biomesoplenty_sacred_oak = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_umbran = null;
//	public static final Block chair_wood_ironage_shield_biomesoplenty_willow = null;
//	
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_cherry = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_ebony = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_ethereal = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_eucalyptus = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_fir = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_hellbark = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_jacaranda = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_magic = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_mahogany = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_mangrove = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_palm = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_pine = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_redwood = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_sacred_oak = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_umbran = null;
//	public static final Block chair_wood_ironage_stool_short_biomesoplenty_willow = null;
//
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_cherry = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_ebony = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_ethereal = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_eucalyptus = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_fir = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_hellbark = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_jacaranda = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_magic = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_mahogany = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_mangrove = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_palm = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_pine = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_redwood = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_sacred_oak = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_umbran = null;
//	public static final Block chair_wood_ironage_stool_tall_biomesoplenty_willow = null;
//	
//	public static final Block chair_wood_ironage_classic_natura_amaranth = null;
//	public static final Block chair_wood_ironage_classic_natura_eucalyptus = null;
//	public static final Block chair_wood_ironage_classic_natura_hopseed = null;
//	public static final Block chair_wood_ironage_classic_natura_maple = null;
//	public static final Block chair_wood_ironage_classic_natura_redwood = null; 
//	public static final Block chair_wood_ironage_classic_natura_sakura = null;
//	public static final Block chair_wood_ironage_classic_natura_silverbell = null;
//	public static final Block chair_wood_ironage_classic_natura_tiger = null;
//	public static final Block chair_wood_ironage_classic_natura_willow = null;
//	public static final Block chair_wood_ironage_classic_natura_bloodwood = null;
//	public static final Block chair_wood_ironage_classic_natura_darkwood = null;
//	public static final Block chair_wood_ironage_classic_natura_fusewood = null;
//	public static final Block chair_wood_ironage_classic_natura_ghostwood = null;
//	
//	public static final Block chair_wood_ironage_shield_natura_amaranth = null;
//	public static final Block chair_wood_ironage_shield_natura_eucalyptus = null;
//	public static final Block chair_wood_ironage_shield_natura_hopseed = null;
//	public static final Block chair_wood_ironage_shield_natura_maple = null;
//	public static final Block chair_wood_ironage_shield_natura_redwood = null; 
//	public static final Block chair_wood_ironage_shield_natura_sakura = null;
//	public static final Block chair_wood_ironage_shield_natura_silverbell = null;
//	public static final Block chair_wood_ironage_shield_natura_tiger = null;
//	public static final Block chair_wood_ironage_shield_natura_willow = null;
//	public static final Block chair_wood_ironage_shield_natura_bloodwood = null;
//	public static final Block chair_wood_ironage_shield_natura_darkwood = null;
//	public static final Block chair_wood_ironage_shield_natura_fusewood = null;
//	public static final Block chair_wood_ironage_shield_natura_ghostwood = null;
//	
//	public static final Block chair_wood_ironage_stool_short_natura_amaranth = null;
//	public static final Block chair_wood_ironage_stool_short_natura_eucalyptus = null;
//	public static final Block chair_wood_ironage_stool_short_natura_hopseed = null;
//	public static final Block chair_wood_ironage_stool_short_natura_maple = null;
//	public static final Block chair_wood_ironage_stool_short_natura_redwood = null; 
//	public static final Block chair_wood_ironage_stool_short_natura_sakura = null;
//	public static final Block chair_wood_ironage_stool_short_natura_silverbell = null;
//	public static final Block chair_wood_ironage_stool_short_natura_tiger = null;
//	public static final Block chair_wood_ironage_stool_short_natura_willow = null;
//	public static final Block chair_wood_ironage_stool_short_natura_bloodwood = null;
//	public static final Block chair_wood_ironage_stool_short_natura_darkwood = null;
//	public static final Block chair_wood_ironage_stool_short_natura_fusewood = null;
//	public static final Block chair_wood_ironage_stool_short_natura_ghostwood = null;
//	
//	public static final Block chair_wood_ironage_stool_tall_natura_amaranth = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_eucalyptus = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_hopseed = null; 
//	public static final Block chair_wood_ironage_stool_tall_natura_maple = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_redwood = null; 
//	public static final Block chair_wood_ironage_stool_tall_natura_sakura = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_silverbell = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_tiger = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_willow = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_bloodwood = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_darkwood = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_fusewood = null;
//	public static final Block chair_wood_ironage_stool_tall_natura_ghostwood = null;
//	
//	public static final Block chair_wood_ironage_classic_immersiveengineering_treatedWood = null;
//	
//	public static final Block chair_wood_ironage_shield_immersiveengineering_treatedWood = null;	
//	
//	public static final Block chair_wood_ironage_stool_short_immersiveengineering_treatedWood = null;
//	
//	public static final Block chair_wood_ironage_stool_tall_immersiveengineering_treatedWood = null;
//
//	public static final Block chair_wood_ironage_classic_forestry_acacia = null;
//	public static final Block chair_wood_ironage_classic_forestry_balsa = null;
//	public static final Block chair_wood_ironage_classic_forestry_baobab = null;
//	public static final Block chair_wood_ironage_classic_forestry_cherry = null;
//	public static final Block chair_wood_ironage_classic_forestry_chestnut = null;
//	public static final Block chair_wood_ironage_classic_forestry_citrus = null;
//	public static final Block chair_wood_ironage_classic_forestry_cocobolo = null;
//	public static final Block chair_wood_ironage_classic_forestry_ebony = null;
//	public static final Block chair_wood_ironage_classic_forestry_giganteum = null;
//	public static final Block chair_wood_ironage_classic_forestry_greenheart = null;
//	public static final Block chair_wood_ironage_classic_forestry_ipe = null;
//	public static final Block chair_wood_ironage_classic_forestry_kapok = null;
//	public static final Block chair_wood_ironage_classic_forestry_larch = null;
//	public static final Block chair_wood_ironage_classic_forestry_lime = null;
//	public static final Block chair_wood_ironage_classic_forestry_mahoe = null;
//	public static final Block chair_wood_ironage_classic_forestry_mahogany = null;
//	public static final Block chair_wood_ironage_classic_forestry_maple = null;
//	public static final Block chair_wood_ironage_classic_forestry_padauk = null;
//	public static final Block chair_wood_ironage_classic_forestry_palm = null;
//	public static final Block chair_wood_ironage_classic_forestry_papaya = null;
//	public static final Block chair_wood_ironage_classic_forestry_pine = null;
//	public static final Block chair_wood_ironage_classic_forestry_plum = null;
//	public static final Block chair_wood_ironage_classic_forestry_poplar = null;
//	public static final Block chair_wood_ironage_classic_forestry_sequoia = null;
//	public static final Block chair_wood_ironage_classic_forestry_teak = null;
//	public static final Block chair_wood_ironage_classic_forestry_walnut = null;
//	public static final Block chair_wood_ironage_classic_forestry_wenge = null;
//	public static final Block chair_wood_ironage_classic_forestry_willow = null;
//	public static final Block chair_wood_ironage_classic_forestry_zebrawood = null;
//
//	public static final Block chair_wood_ironage_shield_forestry_acacia = null;
//	public static final Block chair_wood_ironage_shield_forestry_balsa = null;
//	public static final Block chair_wood_ironage_shield_forestry_baobab = null;
//	public static final Block chair_wood_ironage_shield_forestry_cherry = null;
//	public static final Block chair_wood_ironage_shield_forestry_chestnut = null;
//	public static final Block chair_wood_ironage_shield_forestry_citrus = null;
//	public static final Block chair_wood_ironage_shield_forestry_cocobolo = null;
//	public static final Block chair_wood_ironage_shield_forestry_ebony = null;
//	public static final Block chair_wood_ironage_shield_forestry_giganteum = null;
//	public static final Block chair_wood_ironage_shield_forestry_greenheart = null;
//	public static final Block chair_wood_ironage_shield_forestry_ipe = null;
//	public static final Block chair_wood_ironage_shield_forestry_kapok = null;
//	public static final Block chair_wood_ironage_shield_forestry_larch = null;
//	public static final Block chair_wood_ironage_shield_forestry_lime = null;
//	public static final Block chair_wood_ironage_shield_forestry_mahoe = null;
//	public static final Block chair_wood_ironage_shield_forestry_mahogany = null;
//	public static final Block chair_wood_ironage_shield_forestry_maple = null;
//	public static final Block chair_wood_ironage_shield_forestry_padauk = null;
//	public static final Block chair_wood_ironage_shield_forestry_palm = null;
//	public static final Block chair_wood_ironage_shield_forestry_papaya = null;
//	public static final Block chair_wood_ironage_shield_forestry_pine = null;
//	public static final Block chair_wood_ironage_shield_forestry_plum = null;
//	public static final Block chair_wood_ironage_shield_forestry_poplar = null;
//	public static final Block chair_wood_ironage_shield_forestry_sequoia = null;
//	public static final Block chair_wood_ironage_shield_forestry_teak = null;
//	public static final Block chair_wood_ironage_shield_forestry_walnut = null;
//	public static final Block chair_wood_ironage_shield_forestry_wenge = null;
//	public static final Block chair_wood_ironage_shield_forestry_willow = null;
//	public static final Block chair_wood_ironage_shield_forestry_zebrawood = null;
//	
//	public static final Block chair_wood_ironage_stool_short_forestry_acacia = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_balsa = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_baobab = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_cherry = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_chestnut = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_citrus = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_cocobolo = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_ebony = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_giganteum = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_greenheart = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_ipe = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_kapok = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_larch = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_lime = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_mahoe = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_mahogany = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_maple = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_padauk = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_palm = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_papaya = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_pine = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_plum = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_poplar = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_sequoia = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_teak = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_walnut = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_wenge = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_willow = null;
//	public static final Block chair_wood_ironage_stool_short_forestry_zebrawood = null;
//
//	public static final Block chair_wood_ironage_stool_tall_forestry_acacia = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_balsa = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_baobab = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_cherry = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_chestnut = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_citrus = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_cocobolo = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_ebony = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_giganteum = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_greenheart = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_ipe = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_kapok = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_larch = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_lime = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_mahoe = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_mahogany = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_maple = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_padauk = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_palm = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_papaya = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_pine = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_plum = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_poplar = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_sequoia = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_teak = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_walnut = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_wenge = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_willow = null;
//	public static final Block chair_wood_ironage_stool_tall_forestry_zebrawood = null;
}
