modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="ironagefurniture"
version="${mod_version}" 
displayName="Iron Age Furniture"
description='''${mod_description}'''
authors="SkyBlade1978" 
