modLoader="javafml"
loaderVersion="[64,65)"
license="LGPL-2.1-only"

[[mods]]
modId="ironagefurnitureintegrationprobe"
version="1"
displayName="Iron Age Furniture Optional Integration Probe"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="forge"
mandatory=true
versionRange="[64.0.9,65)"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="minecraft"
mandatory=true
versionRange="[26.1.2]"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="ironagefurniture"
mandatory=true
versionRange="[0.3.0.2601021]"
ordering="AFTER"
side="SERVER"
[[dependencies.ironagefurnitureintegrationprobe]]
modId="biomesoplenty"
mandatory=false
versionRange="[26.1.2.0.22]"
ordering="AFTER"
side="SERVER"

