modLoader="javafml"
loaderVersion="[28,)"
license="LGPL-2.1-only"

[[mods]]
modId="ironagefurnitureintegrationprobe"
version="1"
displayName="Iron Age Furniture Optional Integration Probe"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="forge"
mandatory=true
versionRange="[28.2.26,29)"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="ironagefurniture"
mandatory=true
versionRange="[0.3.0.114041]"
ordering="AFTER"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="biomesoplenty"
mandatory=true
versionRange="[1.14.4-9.0.0.259,)"
ordering="AFTER"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="immersiveengineering"
mandatory=true
versionRange="[0.14-102]"
ordering="AFTER"
side="SERVER"
