modLoader="javafml"
loaderVersion="[45,46)"
license="LGPL-2.1-only"

[[mods]]
modId="ironagefurnitureintegrationprobe"
version="1"
displayName="Iron Age Furniture Optional Integration Probe"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="forge"
mandatory=true
versionRange="[45.4.0,46)"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4]"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="ironagefurniture"
mandatory=true
versionRange="[0.3.0.119041]"
ordering="AFTER"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="biomesoplenty"
mandatory=true
versionRange="[17.3.0.593]"
ordering="AFTER"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="byg"
mandatory=true
versionRange="[4.0.1.3]"
ordering="AFTER"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="immersiveengineering"
mandatory=true
versionRange="[1.19.4-9.4.1-168]"
ordering="AFTER"
side="SERVER"
