modLoader="javafml"
license="LGPL-2.1"

[[mods]]
modId="ironagefurnitureintegrationprobe"
version="1"
displayName="Iron Age Furniture Optional Integration Probe"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="neoforge"
type="required"
versionRange="[26.2.0.45-beta,26.2.1)"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="minecraft"
type="required"
versionRange="[26.2]"
ordering="NONE"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="ironagefurniture"
type="required"
versionRange="[0.3.0.2602002]"
ordering="AFTER"
side="SERVER"

[[dependencies.ironagefurnitureintegrationprobe]]
modId="biomesoplenty"
type="optional"
versionRange="[26.2.0.0.28]"
ordering="AFTER"
side="SERVER"

