name: Upload Release Artifacts

on:
  push:
    tags: [ '*' ]

env:
  JAVA_VERSION: 17
  BUILD_NUMBER: ${{ github.run_number }}
  MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
  MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
  MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
  TAG: ${{ github.ref_name }}

jobs:
  # 1. Extract the short version (e.g. "1.0.0" from "1.20.1-1.0.0")
  prepare:
    name: Prepare Variables
    runs-on: ubuntu-latest
    outputs:
      mod_version: ${{ steps.extract.outputs.version }}
    steps:
      - name: Extract version from tag
        id: extract
        run: |
          FULL_TAG="${{ github.ref_name }}"
          EXTRACTED="${FULL_TAG#*-}"
          echo "version=$EXTRACTED" >> $GITHUB_OUTPUT

  build:
    needs: [prepare]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v7

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Maven Release
        if: ${{ env.MAVEN_UPLOAD_URL }}
        run: ./gradlew publish

      # Upload
      - name: Upload build artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ needs.prepare.outputs.mod_version }}
          path: |
            build/libs/*.jar

  publish_github:
    name: Publish (GitHub Releases)
    needs: [build, prepare]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.event.repository.name }}-${{ needs.prepare.outputs.mod_version }}
          path: build/libs

      - name: Publish (GitHub Releases)
        id: publish_github
        uses: Kira-NT/mc-publish@v3.3.1
        with:
          github-token: ${{ github.token }}
          files: |
            build/libs/*.jar

  publish_platforms:
    name: Publish (${{ matrix.platform }})
    strategy:
      fail-fast: false
      matrix:
        platform: [ 'Curseforge' ]
    needs: [build, prepare]
    runs-on: ubuntu-latest
    # outputs:
      # This is used later when we have a mods.toml or fabric.mods file or so on.
      # curseforge_id: ${{ steps.store_ids.outputs.curseforge_id }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ github.event.repository.name }}-${{ needs.prepare.outputs.mod_version }}
          path: build/libs

      - name: Publish (Curseforge)
        id: publish_curseforge
        if: matrix.platform == 'Curseforge'
        uses: Kira-NT/mc-publish@v3.3.1
        with:
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 238065
          version: ${{ needs.prepare.outputs.mod_version }}
          version-type: beta
          loaders: |
            forge
          environment: client | server
          files: |
            build/libs/!(*-@(sources|javadoc|unused-dev-jar)).jar
            build/libs/*-@(sources|javadoc).jar
